### ISSUE TITLE
[v9.5.*] Cannot find name useI18n

### ISSUE THREAD

**Issue by maxdzin** [nuxt-modules/i18n#3519]
### Environment

(From the Stackblitz reproduction repo)
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.16.2
- CLI Version:      3.24.1
- Nitro Version:    2.11.8
- Package Manager:  pnpm@8.15.6
- Builder:          -
- User Config:      compatibilityDate, devtools, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@9.5.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-jjpn8kps
Run `pnpm typecheck` in the terminal.

### Describe the bug

After update to v9.5.* typecheck fails with an error:
```sh
error TS2304: Cannot find name 'useI18n'.

2 const { locales } = useI18n();
                      ~~~~~~~

Found 1 error in components/LangSwitcher.vue:2


ERROR  Process exited with non-zero status (2)                                      ...
```

### Logs

```shell
❯ pnpm typecheck

> nuxt-app@ typecheck /home/projects/github-jjpn8kps
> nuxi typecheck


 WARN  [nuxt-i18n]: Unable to import oxc-parser, falling back to @oxc-parser/wasm.   11:10:55 AM


 WARN  Slow module @nuxt/devtools took 15917.19ms to setup.                          11:11:11 AM

components/LangSwitcher.vue:2:21 - error TS2304: Cannot find name 'useI18n'.

2 const { locales } = useI18n();
                      ~~~~~~~


Found 1 error in components/LangSwitcher.vue:2


 ERROR  Process exited with non-zero status (2)                                      11:11:42 AM

    at new x (node_modules/.pnpm/tinyexec@1.0.1/node_modules/tinyexec/dist/main.js:440:5)
    at R._waitForOutput (node_modules/.pnpm/tinyexec@1.0.1/node_modules/tinyexec/dist/main.js:548:13)
    at async Object.run (node_modules/.pnpm/@nuxt+cli@3.24.1/node_modules/@nuxt/cli/dist/chunks/typecheck.mjs:61:7)
    at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:337:16)
    at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:328:11)
    at async Module.runMain (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:466:7) 



 ERROR  Process exited with non-zero status (2)                                      11:11:42 AM

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by BobbieGoede** [comment]
Sorry for the regression, expect a patch release soon 🙏

**Comment by BobbieGoede** [comment]
~~This issue is likely still present for auto imports in the nitro context, investigating for a fix.~~
Nitro auto imports are not affected, so should work as expected 😌

Also tracking/discussing in https://github.com/nuxt/nuxt/issues/31674

**Comment by maxdzin** [comment]
Thank you, @BobbieGoede! Fix works!
