### PR TITLE
feat: support nuxt4

### PR DESCRIPTION
**Pull request by kazupon**
### 🔗 Linked issue

#3002 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kazupon** [comment]
Hmm 🤔 
This is strange...  rollup v4.18 could not import resources in relative paths...
https://github.com/nuxt-modules/i18n/actions/runs/9775263922/job/26985312555#step:11:2032

**Comment by kazupon** [comment]
I've added console.log on unplugin-vue-i18n.
I've faced the below log:

```
resolveId ../../../layers/layer-server/app/locales/en.json5 /path/to/Projects/oss/nuxt/i18n/specs/fixtures/basic_usage/.nuxt/___basic_usage_spec_ts/i18n.options.mjs
resolveId ../../../layers/layer-server/app/locales/en.json5 /path/to/Projects/oss/nuxt/i18n/node_modules/.pnpm/nuxt-nightly@4.0.0-28664573.9f4f4d56_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+no_3dkmkqqbk22rzp2kskenwj4dky/node_modules/nuxt-nightly
```

I can't understand why `en.json5` is importing from `nuxt-nightly`. 😅

**Comment by BobbieGoede** [comment]
> I've added console.log on unplugin-vue-i18n. I've faced the below log:
> 
> ```
> resolveId ../../../layers/layer-server/app/locales/en.json5 /path/to/Projects/oss/nuxt/i18n/specs/fixtures/basic_usage/.nuxt/___basic_usage_spec_ts/i18n.options.mjs
> resolveId ../../../layers/layer-server/app/locales/en.json5 /path/to/Projects/oss/nuxt/i18n/node_modules/.pnpm/nuxt-nightly@4.0.0-28664573.9f4f4d56_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+no_3dkmkqqbk22rzp2kskenwj4dky/node_modules/nuxt-nightly
> ```
> 
> I can't understand why `en.json5` is importing from `nuxt-nightly`. 😅

This is due to the folder structure changes in Nuxt 4, I have changed the fixture configurations to use the same structure as Nuxt 3 did using the example shown [here](https://nuxt.com/docs/getting-started/upgrade#new-directory-structure).

The tests will still fail due to other factors, which should be resolved with https://github.com/nuxt-modules/i18n/pull/3015. I made a branch that's rebased on that PR (and main) to demonstrate here: https://github.com/BobbieGoede/i18n/pull/46.

**Comment by BobbieGoede** [comment]
@kazupon 
I have updated/rebased this branch, it looks like it's mostly working except for the nested fixtures.. All fixtures inside `specs/fixtures/issues` fail with `Error: Cannot find module '@nuxtjs/i18n'` 🤔

**Comment by BobbieGoede** [comment]
> @kazupon I have updated/rebased this branch, it looks like it's mostly working except for the nested fixtures.. All fixtures inside `specs/fixtures/issues` fail with `Error: Cannot find module '@nuxtjs/i18n'` 🤔

Fixing this required adding the following to `pnpm-workspace.yaml`:

```
- 'specs/fixtures/issues/*'
```

Not sure why or how it previously worked without issue 🤔 but it looks like all tests succeed now 💪

**Comment by kazupon** [comment]
@BobbieGoede 
Thanks!
Oh, I missed the `srcDir` change ... 🤦‍♂️

The build of the nuxt docs is failing. It seems that nuxt modules that depend on them have not yet been released in a version compatible with nuxt 4.

File: src/module.ts [hunk 1]
```diff
@@ -52,8 +49,7 @@ export default defineNuxtModule<NuxtI18nOptions>({
     name: NUXT_I18N_MODULE_ID,
     configKey: 'i18n',
     compatibility: {
-      nuxt: '>=3.0.0-rc.11',
-      bridge: false
+      nuxt: '>=4.0.0'
```
Comment (BobbieGoede) [inline src/module.ts]:
```suggestion
      nuxt: '>=3.0.0-rc.11'
```

I think with the changes so far we're still compatible with Nuxt 3 too 🤔

**Comment by BobbieGoede** [comment]
Closing since these changes are already included in v9
